theme: jekyll-theme-slate
github:
  repository_url: "https://github.com/rst2pdf/rst2pdf"
title: "rst2pdf"
description: "Use a text editor. Make a PDF"
twitter:
  username: rst2pdf
defaults:
  - scope:
      path: ""
    values:
      image: /images/rst2pdf-header.png
